[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "Au9X2TaJ3Sn8Eg2MmPCzz5U2BLEFfQttqyCLQ2zduH1j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kirtiraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
